input-selector: Add missing dependency on gio-unix-2.0
The build of input-selector may fail otherwise, as the generated code
from gdbus-codegen cannot find the header file <gio/gunixfdlist.h>:

input-selector/org.gnome.Kiosk.c:17:12: fatal error: gio/gunixfdlist.h:
  No such file or directory
  17 | #  include <gio/gunixfdlist.h>

Adding the dependency ensures that the path to the header file is known.