input-source-manager: Fix uninitialized variable
Recent changes introduced a use of an uninitialized variable:

 |  compositor/kiosk-input-sources-manager.c: In function
 |    ‘kiosk_input_sources_manager_set_input_sources_from_locales’:
 |  compositor/kiosk-input-sources-manager.c:1092:12: error:
 |    ‘input_source_group_active’ may be used uninitialized
 |    [-Werror=maybe-uninitialized]
 |  1092 |         if (!input_source_group_active) {
 |       |            ^
 |  compositor/kiosk-input-sources-manager.c:1036:18: note:
 |     ‘input_source_group_active’ was declared here
 |  1036 |         gboolean input_source_group_active;
 |       |                  ^~~~~~~~~~~~~~~~~~~~~~~~~

Fixes: (6489a45a5) - input-source-manager: Don't change active input
source if locked

Part-of: <https://gitlab.gnome.org/GNOME/gnome-kiosk/-/merge_requests/117>